# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 1
gpus: 
distributed_backend:
batch_size: 1

#Non-max supression of overlapping predictions
nms_thresh: 0.05
score_thresh: 0.1

train:

    csv_file:
    root_dir:
    
    #Optomizer  initial learning rate
    lr: 0.001

    #Print loss every n epochs
    epochs: 1
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False
    
    #Trainable backbone layers from https://pytorch.org/vision/0.9/_modules/torchvision/models/detection/retinanet.html
    #trainable_backbone_layers (int): number of trainable (not frozen) resnet layers starting from final block.
    #Valid values are between 0 and 5, with 5 meaning all backbone layers are trainable.
    
    trainable_backbone_layers:
    
validation:
    #callback args
    csv_file: 
    root_dir:
    #Intersection over union evaluation
    iou_threshold: 0.4